version: '3'

services:
  hello_work:
    image: hello_work:v0.1
    build: 
        context: app.hello.work/
        dockerfile: Dockerfile
    container_name: hello_work
    hostname: hello_work
    networks:
      - dev_network
    ports:
      - ${APW_API_PORT}:${APW_API_PORT}
      - ${MON_PORT}:${MON_PORT}
    restart: always
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-fs", "http://localhost:${APW_API_PORT}/healthcheck"]
      interval: 60s
      timeout: 2s
      retries: 3
      # start_period: 15s

  dev_prometheus:
      image: prom/prometheus:latest
      container_name: dev_prometheus
      hostname: dev_prometheus
      volumes:
          - ./prometheus:/etc/prometheus/
      command:
          - --config.file=/etc/prometheus/prometheus.yml
      ports:
          - 9091:9090
      restart: always
      networks: 
          - dev_network

  dev_grafana:
      container_name: dev_grafana
      hostname: dev_grafana
      image: grafana/grafana:6.7.3
      depends_on:
          - dev_prometheus
      user: root
      ports:
          - 3001:3000
      volumes:
          - ./grafana:/var/lib/grafana
          - ./grafana/provisioning/:/etc/grafana/provisioning/
          - ./grafana/setup.sh:/setup.sh
      entrypoint: /setup.sh
      environment:
          - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
          - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
          - GF_PATHS_DATA=/var/lib/grafana
          - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      restart: always
      networks:
          - dev_network

networks:
  dev_network:
    external:
      name: dev_network